import jsPDF from "jspdf";
import logo from "../../assets/common/magnum.png";

export const formatTimestamp = (timestamp) => {
  if (timestamp?.seconds) {
    return new Date(timestamp.seconds * 1000).toLocaleString();
  }
  return "N/A";
};

export const downloadRecordPDF = (booking, activeTab, bookingFields) => {
  const doc = new jsPDF();

  // Header details
  const phoneNumber = "+123-456-7890";
  const email = "info@example.com";

  // Add logo
  doc.addImage(logo, "PNG", 14, 10, 20, 20);

  // Add phone and email
  doc.setFontSize(10);
  doc.text(`Phone: ${phoneNumber}`, 40, 15);
  doc.text(`Email: ${email}`, 40, 20);

  // Add line separator
  doc.setLineWidth(0.5);
  doc.line(14, 30, 196, 30);

  // doc.setFontSize(16);
  // doc.text(`Magnum Hotel`, 80, 28);
  // Title
  doc.setFontSize(16);
  doc.text(`${activeTab}  Details of Magnum Hotel`, 50, 40);

  // Booking details
  const details = bookingFields[activeTab];
  let y = 50; // Initialize vertical position
  doc.setFontSize(12);
  details.forEach((field) => {
    const value = booking[field]?.seconds
      ? formatTimestamp(booking[field]) // Format timestamps
      : booking[field]?.toString();
    doc.text(`${field}: ${value || "N/A"}`, 14, y);
    y += 10;
  });

  // Add items if present
  if (booking.items?.length) {
    doc.text("Items:", 14, y); // Items section title
    y += 10;

    booking.items.forEach((item, index) => {
      const itemDetails = `Item ${index + 1}: ${
        item.name || "N/A"
      } | Category: ${item.category || "N/A"} | Quantity: ${
        item.quantity || "N/A"
      } | Price: ${item.price || "N/A"}`;
      doc.text(itemDetails, 14, y);
      y += 10;
    });
  }

  // Footer details
  const footerText = "Thank you for using our service!";
  const pageHeight = doc.internal.pageSize.height; // Get page height
  doc.setFontSize(10);
  doc.text(footerText, 80, pageHeight - 35);
  doc.text(
    `Page ${doc.internal.getCurrentPageInfo().pageNumber}`,
    196 - 40,
    pageHeight - 20
  );
  doc.text(
    "Generated by MHMS - Magnum Hostel Management System © 2024",
    50,
    pageHeight - 25
  );

  // Save PDF with dynamic file name
  const fileName = `${activeTab}_Booking_${
    booking.bookingId || booking.orderId || "Record"
  }.pdf`;
  doc.save(fileName);
};
